## Introduction to Numpy 

- NumPy's functionalities are implemented in C, a highly efficient programming language.


- This results in significantly faster operations on arrays compared to Python lists. 


-  Machines primarily comprehend ones and zeros, making numeric representations, like those in NumPy, more suitable. In machine learning, data often needs to be converted into numeric formats for easier interpretation by machines. 


In [43]:
import numpy as np

In [44]:
# Numpy min DataTypes is ndarray 
# 1-dimensonal array, also referred to as a vector

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [45]:
type(a1)

numpy.ndarray

In [46]:
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [47]:
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
print("This is 1-D array \n",a1)

This is 1-D array 
 [1 2 3]


In [49]:
print("This is 2-D array \n",a2)

This is 2-D array 
 [[1.  2.  3.3]
 [4.  5.  6.5]]


In [50]:

print("This is 3-D array \n",a3)

This is 3-D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [51]:
# Atanomy(row,col)

a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [52]:
# ndim: 'n' dimension

a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

In [53]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [60]:
# dtype: DataType

a1.dtype, a2.dtype, a2.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [61]:
# size: Total elements

a1.size, a2.size, a3.size

(3, 6, 18)

In [62]:
# type() to determine array type

type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [63]:
# creating a DataFrame from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [66]:
simple_array = np.array ([1,3,6])
simple_array

array([1, 3, 6])

In [67]:
simple_array.dtype

dtype('int64')

In [70]:
# Generate random no. of 1

ones = np.ones((2, 3))

In [71]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
zeros = np.zeros((2, 5))

In [79]:
# .arrage: (start, stop, step)

range_array = np.arange(0, 10, 2)

In [80]:
range_array

array([0, 2, 4, 6, 8])

In [81]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 4, 7, 8, 9],
       [6, 4, 0, 2, 0],
       [1, 0, 9, 6, 6]])

In [82]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.33152909, 0.99919377, 0.72800121],
       [0.56900365, 0.89088132, 0.55283092],
       [0.93082468, 0.21418642, 0.83644947],
       [0.37042105, 0.09299558, 0.36874507],
       [0.99249031, 0.44705955, 0.37821831]])