## Introduction to Numpy 

<span style="color:#666666"> - NumPy's functionalities are implemented in C, a highly efficient programming language.</span>

<span style="color:#666666"> - This results in significantly faster operations on arrays compared to Python lists.</span>

<span style="color:#666666"> - Machines primarily comprehend ones and zeros, making numeric representations, like those in NumPy, more suitable. In machine learning, data often needs to be converted into numeric formats for easier interpretation by machines.</span>


In [2]:
import numpy as np

In [3]:
# Numpy min DataTypes is ndarray 
# 1-dimensonal array, also referred to as a vector

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:


print("This is 1-D array \n",a1)

This is 1-D array 
 [1 2 3]


In [8]:



print("This is 2-D array \n",a2)

This is 2-D array 
 [[1.  2.  3.3]
 [4.  5.  6.5]]


In [9]:

print("This is 3-D array \n",a3)

This is 3-D array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [10]:
# Atanomy(row,col)

a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [11]:
# ndim: 'n' dimension

a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
# dtype: DataType

a1.dtype, a2.dtype, a2.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [14]:
# size: Total elements

a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
# type() to determine array type

type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# creating a DataFrame from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [17]:
simple_array = np.array ([1,3,6])
simple_array

array([1, 3, 6])

In [18]:
simple_array.dtype

dtype('int64')

In [19]:
# ones: This is a function provided by NumPy that generates an array filled with ones.
# ones((row, col))

ones = np.ones((2, 3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
# changed float to int
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
zeros = np.zeros((2, 5))

In [24]:
# .arrage: (start, stop, step)

range_array = np.arange(0, 10, 2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 8, 1, 5, 5],
       [4, 9, 4, 9, 3],
       [9, 4, 4, 2, 0]])

In [27]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.83928007, 0.78872316, 0.75003545],
       [0.16866052, 0.66968209, 0.69541192],
       [0.49048479, 0.49309271, 0.12763743],
       [0.51709693, 0.91330436, 0.3857721 ],
       [0.81556133, 0.31305643, 0.60763285]])

In [28]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.87657121, 0.95279689, 0.25035405],
       [0.08967538, 0.97510223, 0.80954018],
       [0.33518502, 0.46123648, 0.71863132],
       [0.96878964, 0.18483291, 0.97374251],
       [0.40439314, 0.377041  , 0.25437535]])

In [29]:
# pseudo-random numbers: will not change
np.random.seed(0)
random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [30]:
# Now it'll change
random_array_5 = np.random.randint(10, size = (5, 3))
random_array_5

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

## 3. Viewing arrays and matrices (indexing)


In [40]:

a1

array([1, 2, 3])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
# Get 2nd row (index 1) of a2
a2[1]

array([4. , 5. , 6.5])

In [50]:
a2[0]

array([1. , 2. , 3.3])

In [57]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [60]:
a3[:2, :2,]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [61]:
# Breakdown: (2, 3, 4, 5)
# 5: rows, 4: columns, 3: Matrix, 2: sets
# 5-row ke 4-columns 3-set 2- Pair

a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0]],

        [[0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2]],

        [[0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1]]],


       [[[5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7]],

        [[2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6]],

        [[0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0]]]])

In [62]:
a4.shape

(2, 3, 4, 5)

In [63]:
# Get only the first 4 numbers of each single vector

a4[:, :, :, :4]
a4

array([[[[2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0]],

        [[0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2]],

        [[0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1]]],


       [[[5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7]],

        [[2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6]],

        [[0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0]]]])