In [2]:
import numpy as np

## DataType and Attributes

In [3]:
# 1-Dimension array or Vector
a1 = np.array([1, 2, 3])

# 2-Dimension array or Matrix
a2 = np.array([[2, 3, 4],
              [3, 4, 5]])

# 3-Dimension array or Matrix
a3 = np.array([[[2, 4, 4],
               [1, 4, 6],
               [6, 7, 7]],
            [[7, 7, 3],
            [4, 1, 2],
            [5, 6, 6]]])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[2, 3, 4],
       [3, 4, 5]])

In [6]:
a3

array([[[2, 4, 4],
        [1, 4, 6],
        [6, 7, 7]],

       [[7, 7, 3],
        [4, 1, 2],
        [5, 6, 6]]])

In [7]:
# dtype: Used to check the DataType
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [8]:
# type: used to check which type of array 
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [9]:
# ndim: Dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
# shape: return the shape of array (row, col , dim)
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [11]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  2  3  4
1  3  4  5

In [12]:
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), columns=['a', 'b', 'c'])
df

a  b  c
0  1  6  8
1  8  4  4
2  5  8  6
3  8  9  0
4  9  5  4

# Creating arrays

In [13]:
simple_array = np.array([1, 3, 4])
simple_array

array([1, 3, 4])

In [14]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [15]:
ones.dtype

dtype('float64')

In [16]:
# astype: converts into (int)
ones.astype(int)

array([1, 1, 1])

In [17]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [18]:
# arange: returns specific range (start, stop, step)

range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[9, 7, 6],
       [6, 0, 1],
       [8, 1, 0],
       [6, 9, 3],
       [9, 2, 4]])

In [20]:
# random: Generate random floats 0-1
np.random.random((5, 3))

array([[0.35724822, 0.56105398, 0.33117989],
       [0.18380686, 0.8010785 , 0.12385046],
       [0.16302202, 0.71740707, 0.49367423],
       [0.2301328 , 0.53439864, 0.8007733 ],
       [0.24996644, 0.59733432, 0.79344957]])

In [21]:
np.random.rand(5, 3)

array([[0.84003096, 0.52092513, 0.47593418],
       [0.41194117, 0.27394648, 0.06844859],
       [0.09922904, 0.68454566, 0.01491045],
       [0.20489128, 0.40879733, 0.18248646],
       [0.55717662, 0.3424552 , 0.18350509]])

In [22]:
# seed: doesn't change while running
np.random.seed(0)

np.random.randint(10, size=(5, 6))

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0]])

In [23]:
# returns all the unique elements
np.unique(random_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

## Viewing arrays and Matricies

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[2, 3, 4],
       [3, 4, 5]])

In [26]:
a3

array([[[2, 4, 4],
        [1, 4, 6],
        [6, 7, 7]],

       [[7, 7, 3],
        [4, 1, 2],
        [5, 6, 6]]])

In [27]:
a2[0]

array([2, 3, 4])

In [28]:
a3[1]

array([[7, 7, 3],
       [4, 1, 2],
       [5, 6, 6]])

In [29]:
a3[0]

array([[2, 4, 4],
       [1, 4, 6],
       [6, 7, 7]])

In [30]:
a3

array([[[2, 4, 4],
        [1, 4, 6],
        [6, 7, 7]],

       [[7, 7, 3],
        [4, 1, 2],
        [5, 6, 6]]])

In [31]:
a3[: 2, :2, :2]

array([[[2, 4],
        [1, 4]],

       [[7, 7],
        [4, 1]]])

In [39]:
a3[:1, :1]

array([[[2, 4, 4]]])

In [43]:
random_array = np.random.randint(10, size=(5, 4, 2))
random_array

array([[[9, 1],
        [4, 6],
        [8, 2],
        [3, 0]],

       [[0, 6],
        [0, 6],
        [3, 3],
        [8, 8]],

       [[8, 2],
        [3, 2],
        [0, 8],
        [8, 3]],

       [[8, 2],
        [8, 4],
        [3, 0],
        [4, 3]],

       [[6, 9],
        [8, 0],
        [8, 5],
        [9, 0]]])