In [1]:
# importing numpy 

import numpy as np

In [2]:
# 1-Dimensional Array also referred as vector
a1 = np.array([1, 2, 3])

# 2-Dimensional Array also referred to as Matrix
a2 = np.array([[1, 2.0, 3.3],
      [4, 5, 6.5]])

# 3-Dimensional Array also referred to as Matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])


In [3]:
# shape: (row, col)
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [4]:
# ndim: no. of dimensions

a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [5]:
# DataType
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [6]:
# Type : array type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
print("This is a1: \n", a1)
print("This is a2: \n", a2)
print("This is a3: \n", a3)

This is a1: 
 [1 2 3]
This is a2: 
 [[1.  2.  3.3]
 [4.  5.  6.5]]
This is a3: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [8]:
# importing pandas

import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)),
                 columns=['A', 'B', 'C'])

In [9]:
df

A  B  C
0  5  2  4
1  9  1  7
2  5  7  7
3  7  9  3
4  5  3  1

In [10]:
# creating DF of 'a2' array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Creating Array 

In [11]:
simple_array = np.array([2, 4, 6])
simple_array

array([2, 4, 6])

In [12]:
# creating array of ones

ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [14]:
# changing the datatype
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
# creating arrays of zeros

zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# arange: Adding Range (start, stop, step)

arange = np.arange(0, 10, 2)
arange

array([0, 2, 4, 6, 8])

In [17]:
# Random array
random_array = np.random.randint(10, size=(2,4))
random_array

array([[0, 3, 6, 9],
       [9, 6, 8, 6]])

In [18]:
# random: Generates random numbers
np.random.random((5, 3))

array([[0.10868825, 0.18986221, 0.28395372],
       [0.92946694, 0.65727746, 0.80522795],
       [0.00703627, 0.12746587, 0.70757967],
       [0.34652758, 0.50651856, 0.36817751],
       [0.23106235, 0.3886042 , 0.00479622]])

In [19]:
# rand: random no.s
np.random.rand(3,2)

array([[0.73646985, 0.17098789],
       [0.44003929, 0.53651429],
       [0.60682041, 0.57112301]])

In [20]:
# seed() :If you don't want to generate random no.s
np.random.seed(0)

np.random.randint(10, size=(4,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

## Manipulating and Arrays

In [21]:
a1

array([1, 2, 3])

In [22]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [24]:
# Addition
a1 + ones

array([2., 3., 4.])

In [25]:
# Subtraction
a1 - ones

array([0., 1., 2.])

In [26]:
# Multiplication 
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [28]:
a1 * ones

array([1., 2., 3.])

In [29]:
# Throws error a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [32]:
# Division
a1 / ones

array([1., 2., 3.])

In [33]:
# Floor Division
a2 // ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
a1 ** 2

array([1, 4, 9])

In [35]:
np.square(a1)

array([1, 4, 9])

In [ ]:
# mod 
a1 % 